---

- name: install etcd
  hosts: etcdservers
  become: true
  tasks:

  - name: 0 show names
    ansible.builtin.debug:
      msg:
        - "hostname: {{ ansible_hostname }}"
        - "address:  {{ ansible_default_ipv4.address }}"
